# SPDX-License-Identifier: Apache-2.0
"""vLLM KV-cache layout & logical->physical mapping lecture page.

Separate, self-contained HTML page (``kv_cache_layout.html``) generated by
``kv_layout.py``. Independent from the scheduler visualization page.
"""
from __future__ import annotations

from layout.models import build_all_snapshots, build_model_snapshot
from layout.sections import build_page

__all__ = ["build_all_snapshots", "build_model_snapshot", "build_page"]